### ISSUE TITLE
[Bug]: power_factor Unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by O-Palda** [klacol/clage_homeserver#46]
### What happened?

Hi klacol,

I would like to report a bug that is related to the Home Assistant integration, but according to the log, it lays in the clage_homeserver.

I have updated HASS to version 2022.09.1 and latest integration version offered by HACS.

After update two errors appear, one with integration and one with this underlaying library.

` power_factor = device_power / heater_status_powerMax                       # Powerfaktor, siehe Kapitel 4.9 in der API-Dokumentation
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'`

It seems to me, that line 57         device_power = ClageHomeServer.POWERMAX_DSX.get(heater_status_powerMax)   should also be wrapped as float?

Thanks a lot

### Version

1.0.2 (Default)

### Relevant log output

```shell
Unexpected error fetching clage_homeserver data: unsupported operand type(s) for /: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/clage_homeserver/__init__.py", line 129, in fetch_states
    await self._hass.async_add_executor_job(homeserver.requestStatus)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/clage_homeserver/clage_homeserver.py", line 399, in requestStatus
    response = ClageHomeServerMapper().mapApiStatusResponse(status)
  File "/usr/local/lib/python3.10/site-packages/clage_homeserver/clage_homeserver.py", line 58, in mapApiStatusResponse
    power_factor = device_power / heater_status_powerMax                       # Powerfaktor, siehe Kapitel 4.9 in der API-Dokumentation
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by klacol** [comment]
Hi @O-Palda , is this fixed with your [PR 47](https://github.com/klacol/clage_homeserver/pull/47)?

**Comment by klacol** [comment]
Yes, thank you
